contact_links:
  - name: â” Questions / Help
    url: https://github.com/ehsanghaffar/ein-music/discussions
    about: Please use GitHub Discussions for help and questions, do not start an issue.
  - name: ğŸ“ƒ Discord.js Guide
    url: https://discordjs.guide/
    about: The official guide for discord.js
